version: '3.7'

services:
  app:
    build: 
      args:
        user: jadiel
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: example
    container_name: containerName
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - networkName

  webserver: 
    image: nginx:alpine
    container_name: containerName
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - networkName

  db:
    image: mysql:latest
    container_name: containerName
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - networkName

networks:
  networkName:
    driver: bridge

volumes:
  dbdata: